let timer=null,running=false;
async function folders(){const a=await browser.accounts.list(false),o=[];function w(f){if(!f)return;o.push(f);for(const c of f.subFolders||[])w(c)}for(const x of a||[])w(x.rootFolder);return o}
async function scanSentOrders(){try{const a=await browser.accounts.list(false),cutoff=Date.now()-1209600000;for(const x of a||[]){const fs=[];function w(f){if(!f)return;if(String(f.type||"").toLowerCase()==="sent")fs.push(f);for(const c of f.subFolders||[])w(c)}w(x.rootFolder);for(const f of fs){const l=await browser.messages.list(f,{sortType:"date",sortOrder:"descending"});for(const m of l.messages||[]){if(new Date(m.date).getTime()<cutoff)break;await VDMailMonitor.saveOrderFromMessage(m)}}}}catch(e){console.error("Sent-order scan error",e)}}
async function scanIncoming(){if(running)return;running=true;try{await scanSentOrders();if(!(await VDStorage.getOrders()).length)return;const cutoff=Date.now()-604800000;for(const f of await folders()){const l=await browser.messages.list(f,{sortType:"date",sortOrder:"descending"});for(const m of l.messages||[]){if(new Date(m.date).getTime()<cutoff)break;if(await VDStorage.isMessageProcessed(m.id))continue;await VDMailMonitor.processReplyMessage(m)}}}catch(e){console.error("ThunderbirdVidmova scan error",e)}finally{running=false}}
async function processNewMail(folder){try{const l=await browser.messages.list(folder,{sortType:"date",sortOrder:"descending"});for(const m of (l.messages||[]).slice(0,20)){if(!(await VDStorage.isMessageProcessed(m.id)))await VDMailMonitor.processReplyMessage(m)}}catch(e){console.error("New mail processing error",e)}}
function start(){if(timer)clearInterval(timer);timer=setInterval(scanIncoming,45000);scanIncoming()}
browser.runtime.onMessage.addListener(async m=>{if(m?.type==="GET_REFUSALS")return VDStorage.getRefusals();if(m?.type==="GET_ORDERS")return VDStorage.getOrders();if(m?.type==="GET_UNMATCHED")return VDStorage.getUnmatched();if(m?.type==="GET_SUPPLIERS")return VDStorage.getSuppliers();if(m?.type==="GET_PROCESSING_LOG")return VDStorage.getProcessingLog();
if(m?.type==="LEARN_ALIAS"){const orders=await VDStorage.getOrders(),o=orders.find(x=>String(x.orderId)===String(m.orderId));const item=o?.items?.find(x=>String(x.morionCode)===String(m.morionCode));if(!o||!item||!String(m.replyName||"").trim())return{ok:false,error:"Позицію не знайдено"};const unmatched=await VDStorage.getUnmatched(),u=unmatched.find(x=>!x.resolvedAt&&String(x.messageId)===String(m.messageId)&&String(x.orderId)===String(m.orderId)&&String(x.replyName)===String(m.replyName));await VDSupplier.learnAlias(o,m.replyName,item);await VDStorage.resolveUnmatched(m.messageId,m.orderId,m.replyName,item);const ordered=Number(item.orderedQuantity)||0,confirmed=Math.max(0,Math.min(ordered,Number(u?.confirmedQuantity)||0)),refused=Math.max(0,ordered-confirmed);if(refused>0)await VDStorage.upsertRefusal({orderId:o.orderId,morionCode:item.morionCode,name:item.name,refusedQuantity:refused,matchedName:m.replyName,confidence:"manual"});return{ok:true,item,refusedQuantity:refused};}if(m?.type==="CLEAR_REFUSALS"){await VDStorage.saveRefusals([]);return[]}if(m?.type==="SCAN_NOW"){await scanIncoming();return VDStorage.getRefusals()}return null});
if(browser.messages.onNewMailReceived)browser.messages.onNewMailReceived.addListener(processNewMail);
browser.runtime.onStartup.addListener(start);
start();