let timer=null,running=false;
async function folders(type=null){const a=await browser.accounts.list(true),o=[];function w(f){if(!f)return;if(!type||String(f.type||"").toLowerCase()===type)o.push(f);for(const c of f.subFolders||[])w(c)}for(const x of a||[])w(x.rootFolder);return o}
async function messagesSince(folder,cutoff){const out=[];let page=await browser.messages.list(folder);while(page){for(const m of page.messages||[]){const t=new Date(m.date).getTime();if(Number.isFinite(t)&&t>=cutoff)out.push(m)}if(!page.id||typeof browser.messages.continueList!=="function")break;page=await browser.messages.continueList(page.id)}return out}
async function scanSentOrders(sinceDate=null){const stats={sentFolders:0,sentMessages:0,ordersAdded:0,itemsAdded:0,alreadyStored:0,parseFailed:0,messagesWithAttachments:0,attachmentTypes:{},unparsedSamples:[]};try{const a=await browser.accounts.list(true),cutoff=sinceDate?new Date(sinceDate+"T00:00:00").getTime():Date.now()-1209600000;for(const x of a||[]){const fs=[];function w(f){if(!f)return;if(String(f.type||"").toLowerCase()==="sent")fs.push(f);for(const c of f.subFolders||[])w(c)}w(x.rootFolder);for(const f of fs){stats.sentFolders++;const ms=await messagesSince(f,cutoff);stats.sentMessages+=ms.length;for(const m of ms){const before=await VDStorage.getOrders(),exists=before.some(o=>o.messageId===m.id);if(exists){stats.alreadyStored++;continue}let attachments=[];try{attachments=await browser.messages.listAttachments(m.id)||[]}catch(e){console.warn("Cannot list attachments",m.id,e)}if(attachments.length)stats.messagesWithAttachments++;for(const at of attachments){const ext=(String(at.name||"").match(/\.([^.]+)$/)||[])[1];const key=ext?ext.toLowerCase():"(без розширення)";stats.attachmentTypes[key]=(stats.attachmentTypes[key]||0)+1}const o=await VDMailMonitor.saveOrderFromMessage(m);if(o){stats.ordersAdded++;stats.itemsAdded+=o.items.length}else{stats.parseFailed++;if(stats.unparsedSamples.length<12){let bodyLength=0;try{bodyLength=(await VDMailMonitor.extractMessageText(m.id)).length}catch(_){}stats.unparsedSamples.push({date:m.date,subject:m.subject||"",author:m.author||"",attachments:attachments.map(z=>z.name||"(без назви)"),bodyLength})}}}}}catch(e){console.error("Sent-order scan error",e);stats.error=String(e)}return stats}
async function scanIncoming(sinceDate=null){if(running)return{busy:true};running=true;const stats={};try{stats.sent=await scanSentOrders(sinceDate);stats.ordersTotal=(await VDStorage.getOrders()).length;stats.inboxFolders=0;stats.inboxMessages=0;stats.repliesProcessed=0;{const cutoff=sinceDate?new Date(sinceDate+"T00:00:00").getTime():Date.now()-604800000;for(const f of await folders("inbox")){stats.inboxFolders++;const ms=await messagesSince(f,cutoff);stats.inboxMessages+=ms.length;if(stats.ordersTotal){for(const m of ms){if(await VDStorage.isMessageProcessed(m.id))continue;await VDMailMonitor.processReplyMessage(m);stats.repliesProcessed++}}}}}catch(e){console.error("ThunderbirdVidmova scan error",e);stats.error=String(e)}finally{running=false}return stats}
async function processNewMail(folder){try{if(String(folder?.type||"").toLowerCase()!=="inbox")return;const l=await browser.messages.list(folder,{sortType:"date",sortOrder:"descending"});for(const m of (l.messages||[]).slice(0,20)){if(!(await VDStorage.isMessageProcessed(m.id)))await VDMailMonitor.processReplyMessage(m)}}catch(e){console.error("New mail processing error",e)}}
globalThis.VDScanInternals={messagesSince,folders};
function start(){if(timer)clearInterval(timer);timer=setInterval(scanIncoming,45000);scanIncoming()}
browser.runtime.onMessage.addListener(async m=>{if(m?.type==="GET_REFUSALS")return VDStorage.getRefusals();if(m?.type==="GET_ORDERS")return VDStorage.getOrders();if(m?.type==="GET_UNMATCHED")return VDStorage.getUnmatched();if(m?.type==="GET_SUPPLIERS")return VDStorage.getSuppliers();if(m?.type==="GET_PROCESSING_LOG")return VDStorage.getProcessingLog();
if(m?.type==="LEARN_ALIAS"){const orders=await VDStorage.getOrders(),o=orders.find(x=>String(x.orderId)===String(m.orderId));const item=o?.items?.find(x=>String(x.morionCode)===String(m.morionCode));if(!o||!item||!String(m.replyName||"").trim())return{ok:false,error:"Позицію не знайдено"};await VDSupplier.learnAlias(o,m.replyName,item,"manual");const result=await VDMailMonitor.reprocessUnmatchedMessage(m.messageId,m.orderId);return{ok:true,item,...result};}if(m?.type==="CLEAR_REFUSALS"){await VDStorage.saveRefusals([]);return[]}if(m?.type==="SCAN_NOW"){const stats=await scanIncoming();return{stats,refusals:await VDStorage.getRefusals()}}if(m?.type==="SCAN_FROM_DATE"){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(m.date||"")))return{ok:false,error:"Вкажіть дату початку перевірки"};const stats=await scanIncoming(m.date);return{ok:true,stats,refusals:await VDStorage.getRefusals()}}return null});
if(browser.messages.onNewMailReceived)browser.messages.onNewMailReceived.addListener(processNewMail);
browser.runtime.onStartup.addListener(start);
start();