function supplierKey(author){const s=String(author||"").toLowerCase();const m=s.match(/<([^>]+)>/);return(m?m[1]:s).trim()}
function aliasKey(x){return VDNormalizer.normalizeProductName(x)}
function aliasCode(x){return String(x??"").trim().toUpperCase().replace(/[\s._\/-]+/g,"")}
async function learnSupplier(order,attachmentNames=[]){const key=supplierKey(order.supplier);if(!key)return;const ext={};for(const n of attachmentNames){const x=String(n).toLowerCase().match(/\.(xlsx|xls|csv)$/);if(x)ext[x[1]]=(ext[x[1]]||0)+1}await VDStorage.upsertSupplier({key,displayName:order.supplier,subjectExample:order.subject,attachmentTypes:ext,itemsCount:order.items?.length||0})}
async function learnReplyFormat(order,format,signature=""){const key=supplierKey(order.supplier);if(!key||!format||!signature)return;const a=await VDStorage.getSuppliers(),p=a.find(x=>x.key===key),history=Array.isArray(p?.replyFormatHistory)?p.replyFormatHistory.slice():[],now=new Date().toISOString(),i=history.findIndex(x=>x.signature===signature);let entry;if(i>=0){entry={...history[i],uses:Number(history[i].uses||0)+1,lastSeen:now,format};history[i]=entry}else{entry={signature,uses:1,firstSeen:now,lastSeen:now,format};history.push(entry)}
const current=p?.replyFormat||null;
let stable=current;
if(!stable?.signature)stable=entry;
else if(stable.signature===signature)stable={...stable,...entry};
else if(entry.uses>=2)stable=entry;
history.sort((x,y)=>{const u=Number(y.uses||0)-Number(x.uses||0);return u||String(y.lastSeen||"").localeCompare(String(x.lastSeen||""))});
await VDStorage.upsertSupplier({key,replyFormat:{...stable.format,signature:stable.signature,learnedAt:stable.lastSeen,uses:stable.uses},replyFormatHistory:history.slice(0,5)})}
async function getReplyFormat(order){const key=supplierKey(order.supplier),a=await VDStorage.getSuppliers(),p=a.find(x=>x.key===key);return p?.replyFormat||null}
async function learnAlias(order,replyName,item,confidence="manual"){const key=supplierKey(order.supplier),alias=aliasKey(replyName),code=String(item?.morionCode||"").trim();if(!key||!alias||!code)return false;if(confidence==="high")return false;const a=await VDStorage.getSuppliers(),p=a.find(x=>x.key===key),aliases={...(p?.aliases||{})},old=aliases[alias],normalized=aliasCode(code);if(!old){aliases[alias]={morionCode:code,name:item.name,uses:1,lastConfidence:confidence};await VDStorage.upsertSupplier({key,aliases});return true}if(aliasCode(old.morionCode)===normalized){const updated={...old,name:item.name,uses:Number(old.uses||0)+1,lastConfidence:confidence};delete updated.candidateMorionCode;delete updated.candidateName;delete updated.candidateUses;aliases[alias]=updated;await VDStorage.upsertSupplier({key,aliases});return true}if(confidence==="manual"){aliases[alias]={morionCode:code,name:item.name,uses:1,lastConfidence:confidence};await VDStorage.upsertSupplier({key,aliases});return true}const candidateCode=aliasCode(old.candidateMorionCode)===normalized?old.candidateMorionCode:code;const candidateUses=(aliasCode(old.candidateMorionCode)===normalized?Number(old.candidateUses||0):0)+1;if(candidateUses>=2)aliases[alias]={morionCode:code,name:item.name,uses:1,lastConfidence:confidence};else aliases[alias]={...old,candidateMorionCode:candidateCode,candidateName:item.name,candidateUses};await VDStorage.upsertSupplier({key,aliases});return true}
async function resolveAlias(order,replyName){const key=supplierKey(order.supplier),alias=aliasKey(replyName),a=await VDStorage.getSuppliers(),p=a.find(x=>x.key===key),hit=p?.aliases?.[alias];if(!hit)return null;return order.items.find(x=>aliasCode(x.morionCode)===aliasCode(hit.morionCode))||null}
globalThis.VDSupplier={supplierKey,learnSupplier,learnAlias,resolveAlias,learnReplyFormat,getReplyFormat};