let state={tab:"refusals",refusals:[],orders:[],unmatched:[],suppliers:[]};
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function load(){state.refusals=await browser.runtime.sendMessage({type:"GET_REFUSALS"});state.orders=await browser.runtime.sendMessage({type:"GET_ORDERS"});state.unmatched=await browser.runtime.sendMessage({type:"GET_UNMATCHED"});state.suppliers=await browser.runtime.sendMessage({type:"GET_SUPPLIERS"});render()}
function render(){document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===state.tab));const data=state[state.tab],s=state.tab==="refusals"?`Відмов: ${data.length} • од.: ${data.reduce((n,x)=>n+Number(x.refusedQuantity||0),0)}`:state.tab==="orders"?`Замовлень: ${data.length}`:state.tab==="unmatched"?`Невпізнаних: ${data.length}`:`Постачальників: ${data.length}`;$("#stats").textContent=s;let h="";if(state.tab==="refusals"){h="<table><thead><tr><th>Назва</th><th>Код Моріона</th><th class='num'>Відмовлено</th><th>Впевненість</th></tr></thead><tbody>"+data.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.morionCode)}</td><td class='num danger'>${x.refusedQuantity}</td><td>${esc(x.confidence)}</td></tr>`).join("")+"</tbody></table>"}else if(state.tab==="orders"){h="<table><thead><tr><th>Дата</th><th>Постачальник</th><th>Тема</th><th class='num'>Позицій</th></tr></thead><tbody>"+data.map(x=>`<tr><td>${esc(new Date(x.date).toLocaleString("uk-UA"))}</td><td>${esc(x.supplier)}</td><td>${esc(x.subject)}</td><td class='num'>${x.items?.length||0}</td></tr>`).join("")+"</tbody></table>"}else if(state.tab==="unmatched"){h="<table><thead><tr><th>Позиція у відповіді</th><th>Замовлення</th><th class='num'>Score</th><th>Дата</th></tr></thead><tbody>"+data.map(x=>`<tr><td>${esc(x.replyName)}</td><td>${esc(x.orderId)}</td><td class='num'>${Number(x.bestScore||0).toFixed(3)}</td><td>${esc(new Date(x.seenAt).toLocaleString("uk-UA"))}</td></tr>`).join("")+"</tbody></table>"}else{h="<table><thead><tr><th>Постачальник</th><th>Аліасів</th><th>Формати</th><th>Остання активність</th></tr></thead><tbody>"+data.map(x=>`<tr><td>${esc(x.displayName||x.key)}</td><td>${Object.keys(x.aliases||{}).length}</td><td>${Object.keys(x.attachmentTypes||{}).join(", ")||"-"}</td><td>${esc(new Date(x.lastSeen||x.firstSeen).toLocaleString("uk-UA"))}</td></tr>`).join("")+"</tbody></table>"}$("#content").innerHTML=h||"<div class='empty'>Немає даних</div>"}
function currentRows(){if(state.tab==="refusals")return state.refusals.map(x=>[x.name,x.morionCode,x.refusedQuantity]);if(state.tab==="suppliers")return state.suppliers.map(x=>[x.displayName||x.key,Object.keys(x.aliases||{}).length,Object.keys(x.attachmentTypes||{}).join(", ")]);if(state.tab==="orders")return state.orders.flatMap(o=>o.items.map(i=>[o.date,o.supplier,i.name,i.morionCode,i.orderedQuantity]));return state.unmatched.map(x=>[x.replyName,x.orderId,x.bestScore,x.seenAt])}
function csv(rows){return rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(";")).join("\r\n")}
function download(name,text){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});
$("#scan").onclick=async()=>{$("#status").textContent="Перевірка...";await browser.runtime.sendMessage({type:"SCAN_NOW"});await load();$("#status").textContent="Готово"};
async function copyOrder(){const text=state.refusals.map(x=>`${x.morionCode}\t${x.refusedQuantity}`).join("\n");await navigator.clipboard.writeText(text);$("#status").textContent="Код Моріона + кількість скопійовано"}\n$("#copy").onclick=async()=>{await copyOrder()};
$("#export").onclick=()=>download(`thunderbird-vidmova-${state.tab}.csv`,csv(currentRows()));
$("#clear").onclick=async()=>{await browser.runtime.sendMessage({type:"CLEAR_REFUSALS"});await load();$("#status").textContent="Відмови очищено"};
load();